import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import { Toaster } from "@/components/ui/toaster";
import { DeviceIdProvider } from "@/components/DeviceIdProvider/DeviceIdProvider";
import { UserProvider } from "@/contexts/UserContext";
import { AuthCheck } from "@/components/AuthCheck";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-br from-blue-900 via-slate-800 to-gray-900`}
      >
        <UserProvider>
          <DeviceIdProvider>
            <Header />
            <div className="w-full h-[calc(100vh-70px)] mt-[70px] overflow-auto">
              <AuthCheck>{children}</AuthCheck>
            </div>
            <Toaster />
          </DeviceIdProvider>
        </UserProvider>
      </body>
    </html>
  );
}
